apiVersion: v1
kind: Service
metadata:
  name: go-ingress-accounts-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30300
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: accounts