apiVersion: v1
kind: Service
metadata:
  name: go-ingress-customers-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30302
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: customers