apiVersion: v1
kind: ReplicationController
metadata:
  name: go-simple-replica-set
spec:
  replicas: 2
  selector:
    app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: go-simple
          image: gcr.io/williamscj-gke-demos/go-simple:latest
          ports:
            - containerPort: 3000
