apiVersion: v1
kind: Pod
metadata:
  name: go-simple-pod
  labels:
    app: simple
spec:
  containers:
    - name: go-simple
      image: gcr.io/williamscj-gke-demos/go-simple:latest
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 30
  nodeSelector:
      hardware: high-spec
