apiVersion: v1
kind: Service
metadata:
  name: go-ingress-banks-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30301
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: banks