apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mysql-vol-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mysql-vol-deploy
  template:
    metadata:
      labels:
        app: go-mysql-vol-deploy
    spec:
      containers:
        - name: go-vol
          image: gcr.io/williamscj-gke-demos/go-volumes:v2
          #command: ["node", "index-db.js"]
          ports:
            - name: go-port
              containerPort: 8080
          env:
            - name: MYSQL_HOST
              #this is the mysql service discovery being called
              value: mysql-vol-svc
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-vol-secrets
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-vol-secrets
                  key: database
