apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol-database
  labels:
    app: mysql-vol-database
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - name: mysql-port
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-vol-secrets
              key: rootPassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-vol-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-vol-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-vol-secrets
              key: database
      #mount volume to /var/lib/mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          #use a subPath on the volumeMounts object. This uses a subdirectory of the PersistentVolume,
          #which should be empty at creation time, instead of the volume root:
          subPath: mysql
  #Create volume based on pvc mysql-volumeclaim
  #GKE create a volume using persistent disk
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-volumeclaim